FROM python:3.10
MAINTAINER saqpsaqp@gmail.com

ENV PYTHONUNBUFFERRED 1

ADD requirements.txt requirements.txt

# Global Protect SSL Issue
COPY ./localdev/cert_ca-lulobank-auto-sign.crt /root/cert_ca-lulobank-auto-sign.crt
RUN cat /root/cert_ca-lulobank-auto-sign.crt >> /etc/ssl/certs/ca-certificates.crt
COPY ./localdev/cert_ca-lulobank-auto-sign.crt /usr/local/share/ca-certificates
RUN update-ca-certificates

# Unsafe Renegotiation request
COPY openssl_conf.cnf /root/openssl_conf.cnf
ENV OPENSSL_CONF /root/openssl_conf.cnf

RUN apt update && apt upgrade -y
RUN apt install -y xmlsec1 gcc libffi-dev libxslt1-dev libxml2-dev

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install -r requirements.txt

RUN mkdir /secrets
RUN mkdir /app
RUN mkdir -p /www/media
VOLUME /www/media

WORKDIR /app
ADD app /app

EXPOSE 8080
