FROM python:3.10-alpine
MAINTAINER saqpsaqp@gmail.com

ENV PYTHONUNBUFFERRED 1

ADD requirements.txt requirements.txt

# Global Protect SSL Issue
COPY ./localdev/cert_ca-lulobank-auto-sign.crt /root/cert_ca-lulobank-auto-sign.crt
RUN cat /root/cert_ca-lulobank-auto-sign.crt >> /etc/ssl/certs/ca-certificates.crt
RUN apk --no-cache add ca-certificates \
    && rm -rf /var/cache/apk/*
COPY ./localdev/cert_ca-lulobank-auto-sign.crt /usr/local/share/ca-certificates
RUN update-ca-certificates

# Unsafe Renegotiation request
COPY openssl_conf.cnf /root/openssl_conf.cnf
ENV OPENSSL_CONF /root/openssl_conf.cnf

RUN apk add --update --no-cache xmlsec gcc

RUN apk add --update --no-cache --virtual .tmp-build-deps \
    gcc libc-dev linux-headers libffi-dev

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install -r requirements.txt

RUN mkdir /secrets
RUN mkdir /app
RUN mkdir -p /www/media
VOLUME /www/media

WORKDIR /app
ADD app /app

EXPOSE 8080
